### ISSUE TITLE
Question about Monitor placement

### ISSUE THREAD

**Issue by rhyn0rang3r** [buzz/devilspy#4]
If i wanted discord to be opened on a certain monitor and at a certain size how would i do this?

**Comment by buzz** [comment]
First you need a rule that reliably matches the target window(s). You can make devilspy to print relevant window information on the command line.

    $ devilspy --print-window-info

From the [Gdk documentation](https://lazka.github.io/pgi-docs/#Gdk-3.0/classes/Screen.html#Gdk.Screen):

> X originally identified screens with physical screens, but nowadays it is more common to have a single `Gdk.Screen` which combines several physical monitors

This means, you most likely have one big virtual screen combining all of your physical monitors. Thus you just need to set the window position accordingly. The following config snippet puts the discord windows to the top left corner of my second screen (my first screen has a horizontal resolution of 1920 pixels).

```
discord:
  rules:
    - class_group: discord
    - app_name: Discord
  actions:
    - position_wm: [1920, 0]
```
